[package]
name = "robotfindskitten"
version = "0.1.0"
edition = "2015"

[dependencies]
rand = "0.5.5"
ncurses = "=5.86.0"
libc = "0.2"

[dev-dependencies]
expectrl = "0.7"
vte = "0.12"
regex = "1"

[[test]]
name = "test"
path = "tests/test.rs"
harness = true

